name: ec2-terraform-demo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  planandapply:
    runs-on: codebuild-githubactions-codebuild-terraform-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
    - run: terraform init
    - id: plan
      run: terraform plan -no-color
    - id: apply
      run: terraform apply -auto-approve
    
